name: etahlil
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # 1.Connection checker
  internet_connection_checker: ^0.0.1+3
  # 2.Service Locator
  get_it: ^7.2.0
  # 3.State Management
  flutter_bloc: ^8.0.1
  # 4.Network calls
  http: ^0.13.4
  # 5.Local cache
  shared_preferences: ^2.0.13
  # 6.Local database
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  # 7.Message viewer
  fluttertoast: ^8.0.8
  # 8.Support svg icons
  flutter_svg: ^1.0.3
  # 9.Support text sizes
  auto_size_text: ^3.0.0
  # 10.Responsive ui
  flutter_screenutil: ^5.2.0
  # 11.Formatter
  mask_text_input_formatter: ^2.1.0
  # 12.PinCode helper
  pin_code_fields: ^7.0.0-nullsafety
  # 13.Bloc cached clear helper
  bloc_concurrency: ^0.2.0
  # 14.Image picker from camera
  image_picker: ^0.8.4+9
  # 15.intro views images
  carousel_slider: ^4.0.0
  # 16. For get current time and others
  intl: ^0.17.0
  # 17.Value equality
  equatable: ^2.0.3
  # 18.Functional programming thingies
  dartz: ^0.10.1
  # 19.For get uni address
  device_info_plus: ^3.2.2
  # 19.For get current location
  geolocator: ^8.2.0
  # 19.For Image cached
  cached_network_image: ^3.2.0
  # 20.For Progress
  sn_progress_dialog: ^1.0.3
  # 21. For Fingerprint
  local_auth: ^1.1.0
  # 22 For stream
  rxdart: ^0.27.3
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  # 1.For Splash
  flutter_native_splash: ^2.0.3+1

  # 1.For Local database
  build_runner: ^2.1.7
  hive_generator: ^1.1.2

flutter_native_splash:
  color: '#2972FE'
  image: assets/images/logoTahlil.png
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: SemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf